FROM golang:1.17 AS build
WORKDIR /httpserver/
COPY . .
ENV CGO_ENABLED=0 \
	GO111MODULE=on \
	GOPROXY=https://goproxy.cn,direct
RUN GOOS=linux go build -installsuffix cgo -o httpserver main.go

FROM scratch
COPY --from=build /httpserver/httpserver /httpserver/httpserver
EXPOSE 80
WORKDIR /httpserver/
ENTRYPOINT ["./httpserver"]
